# Kameron's jekyll config
# vim: set ft=yaml et ts=2 sts=2 :

# Configuration
permalink: "/:categories/:year/:month/:day/:title/"
markdown: kramdown
hilighter: pygments
lsi: false
exclude: [.gitignore, _config.yml, _libraries, Makefile, tidy.log, old]
gems:
  - jekyll-sitemap

# Custom variables
title: "~kameron"
url: "http://thelinux.pro"
keywords: "Kameron,Kenny,Kameron Kenny,blog,programming,coding,personal,homepage"

# Author information
author:
  name: "Kameron Kenny"
  #mail: "Someone@Somewhere.net"
  github: "kkenny"
  linkedin: "kameronkenny"
  twitter: "kameronkenny"

# Feeds
#rss:
#  all: ""

# Tags
tag:
  cloud:
    levels: 15
    limit:  100

  list:
    en: en/tags/index.html
